CREATE TABLE IF NOT EXISTS "tb_order_producer"
(
    "id"                  SERIAL    NOT NULL,
    "identify"            VARCHAR   NOT NULL,
    "created_at"          TIMESTAMP NOT NULL,
    "limit_delivery_date" INTEGER   DEFAULT NULL,
    "delivery_date"       TIMESTAMP NOT NULL,
    "corporate_name"      VARCHAR   NULL DEFAULT NULL,
    "name"                VARCHAR   NOT NULL,
    "cpf"                 VARCHAR   NOT NULL,
    "cnpj"                VARCHAR   NOT NULL,
    "address"             VARCHAR   NULL DEFAULT NULL,
    "comments"            TEXT      NULL DEFAULT NULL,
    "box_type"            VARCHAR   NOT NULL,
    "responsible"         VARCHAR   NULL DEFAULT NULL,
    "service_grantor"     VARCHAR   NULL DEFAULT NULL,
    "length"              INTEGER   NOT NULL,
    "width"               INTEGER   NOT NULL,
    "height"              INTEGER   NOT NULL,
    "value_length_calc"   INTEGER    NOT NULL,
    "value_width_calc"    INTEGER    NOT NULL,
    "value_height_calc"   INTEGER    NOT NULL,
    "value_aba_sup"       INTEGER    DEFAULT NULL,
    "value_aba_sub"       INTEGER    DEFAULT NULL,
    "dilated_length_one"  INTEGER    NOT NULL,
    "dilated_width_one"   INTEGER    NOT NULL,
    "dilated_length_two"  INTEGER    NOT NULL,
    "dilated_width_two"   INTEGER    NOT NULL,
    "dilated_height"      INTEGER    NOT NULL,
    "dilated_abas_sup"    INTEGER    NOT NULL,
    "dilated_abas_sub"    INTEGER    NOT NULL,
    PRIMARY KEY ("id")
);