CREATE TABLE IF NOT EXISTS TB_ORDER_PRODUCER
(
    ID                  SERIAL  NOT NULL ,
    IDENTIFY            VARCHAR   NOT NULL,
    CREATED_AT          TIMESTAMP NOT NULL,
    LIMIT_DELIVERY_DATE TIMESTAMP   NOT NULL,
    DELIVERY_DATE       TIMESTAMP NOT NULL,
    CORPORATE_NAME      VARCHAR   NULL,
    NAME                VARCHAR   NOT NULL,
    CPF                VARCHAR   NOT NULL,
    CNPJ                VARCHAR   NOT NULL,
    ADDRESS             VARCHAR   NULL,
    COMMENTS            TEXT      NULL,
    BOX_TYPE            VARCHAR   NOT NULL,
    RESPONSIBLE         VARCHAR   NULL,
    SERVICE_GRANTOR     VARCHAR   NULL,
    LENGTH     INTEGER  NULL,
    WIDTH      INTEGER  NULL,
    HEIGHT     INTEGER  NULL,

    VALUE_LENGTH_CALC   INTEGER   NULL,
    VALUE_WIDTH_CALC    INTEGER   NULL,
    VALUE_HEIGHT_CALC   FLOAT     NULL,

    VALUE_ABA_SUP       INTEGER   NULL,
    VALUE_ABA_SUB       INTEGER   NULL,

    DILATED_LENGTH_ONE  INTEGER   NULL,
    DILATED_WIDTH_ONE   INTEGER   NULL,
    DILATED_LENGTH_TWO  INTEGER   NULL,
    DILATED_WIDTH_TWO   INTEGER   NULL,
    DILATED_HEIGHT_TWO  INTEGER   NULL,

    DILATED_ABAS_SUP    INTEGER   NULL,
    DILATED_ABAS_SUB    INTEGER   NULL,
    PRIMARY KEY (ID)
)